version: "2.4"
services:
    app:
        container_name: swift_tensorflow_raw
        build:
            context: ./
            dockerfile: "Dockerfile_raw"
        working_dir: /usr/src/app
        volumes:
            - ./:/usr/src/app
        runtime: nvidia
        privileged: true
        networks:
            - app_net

networks:
    app_net:
        driver: bridge
